logging:
  level:
    hu.zza.yeelan.controller: TRACE
    hu.zza.yeelan.service: TRACE
    hu.zza.yeelan.service.factory: INFO
    hu.zza.yeelan.service.resolver: TRACE


config:
  device:
    list:
      desk:
        address: 192.168.1.107
        property_profile: [basic, night]
      shelf:
        address: 192.168.1.108
        property_profile: basic
    property_profile:
      basic: [POWER, BRIGHT, CT, COLOR_MODE]
      night: [ACTIVE_MODE, NL_BR]

  light:
    day:
      min: 1
      low: 20
      mean: 35
      mid: 50
      great: 70
      max: 100
    night:
      min: 1
      moon: 2
      night: 10
      light: 25
      mid: 50
      max: 100